[package]
name = "cli-api-caller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
csv = "1.2.2"
derive = "1.0.0"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.24.1"
rustls = "0.21.7"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tokio = { version = "1", features = ["full"] }
toml = "0.7.6"
